//Get - User
export const USER_GET_REQUEST = "USER_GET_REQUEST"
export const USER_GET_SUCCESS = "USER_GET_SUCCESS"
export const USER_GET_FAIL = "USER_GET_FAIL"

//Post - User
export const USER_POST_REQUEST = "USER_GET_REQUEST"
export const USER_POST_SUCCESS = "USER_GET_SUCCESS"
export const USER_POST_FAIL = "USER_GET_FAIL"

//delete - User
export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST"
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS"
export const USER_DELETE_FAIL = "USER_DELETE_FAIL"

//add-party data
export const PARTY_POST_REQUEST = "PARTY_POST_REQUEST"
export const PARTY_POST_SUCCESS = "PARTY_POST_SUCCESS"
export const PARTY_POST_FAIL = "PARTY_POST_FAIL"

//get-party data
export const PARTY_GET_REQUEST = "PARTY_GET_REQUEST"
export const PARTY_GET_SUCCESS = "PARTY_GET_SUCCESS"
export const PARTY_GET_FAIL = "PARTY_GET_FAIL"

//delete-party data
export const PARTY_DELETE_REQUEST = "PARTY_DELETE_REQUEST"
export const PARTY_DELETE_SUCCESS = "PARTY_DELETE_SUCCESS"
export const PARTY_DELETE_FAIL = "PARTY_DELETE_FAIL"

//get-election data
export const ELECTION_GET_REQUEST = "ELECTION_GET_REQUEST"
export const ELECTION_GET_SUCCESS = "ELECTION_GET_SUCCESS"
export const ELECTION_GET_FAIL = "ELECTION_GET_FAIL"

//add-election data
export const ELECTION_POST_REQUEST = "ELECTION_POST_REQUEST"
export const ELECTION_POST_SUCCESS = "ELECTION_POST_SUCCESS"
export const ELECTION_POST_FAIL = "ELECTION_POST_FAIL"

//delete-party data
export const ELECTION_DELETE_REQUEST = "ELECTION_DELETE_REQUEST"
export const ELECTION_DELETE_SUCCESS = "ELECTION_DELETE_SUCCESS"
export const ELECTION_DELETE_FAIL = "ELECTION_DELETE_FAIL"
