//Post - ADMIN_LoginData
export const ADMIN_LOGIN_POST_REQUEST = "ADMIN_LOGIN_GET_REQUEST"
export const ADMIN_LOGIN_POST_SUCCESS = "ADMIN_LOGIN_GET_SUCCESS"
export const ADMIN_LOGIN_POST_FAIL = "ADMIN_LOGIN_GET_FAIL"

export const ADMIN_LOGOUT_POST_SUCCESS = "ADMIN_LOGOUT_GET_SUCCESS"
export const USER_LOGIN = "USER_LOGIN"
export const USER_LOGOUT = "USER_LOGOUT"

//Post - User_LoginData
export const USER_LOGIN_POST_REQUEST = "USER_LOGIN_GET_REQUEST"
export const USER_LOGIN_POST_SUCCESS = "USER_LOGIN_GET_SUCCESS"
export const USER_LOGIN_POST_FAIL = "USER_LOGIN_GET_FAIL"

//Get - User
export const USER_GET_REQUEST = "USER_GET_REQUEST"
export const USER_GET_SUCCESS = "USER_GET_SUCCESS"
export const USER_GET_FAIL = "USER_GET_FAIL"

//Post - User
export const USER_POST_REQUEST = "USER_GET_REQUEST"
export const USER_POST_SUCCESS = "USER_GET_SUCCESS"
export const USER_POST_FAIL = "USER_GET_FAIL"

//delete - User
export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST"
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS"
export const USER_DELETE_FAIL = "USER_DELETE_FAIL"

//add-party data
export const PARTY_POST_REQUEST = "PARTY_POST_REQUEST"
export const PARTY_POST_SUCCESS = "PARTY_POST_SUCCESS"
export const PARTY_POST_FAIL = "PARTY_POST_FAIL"

//get-party data
export const PARTY_GET_REQUEST = "PARTY_GET_REQUEST"
export const PARTY_GET_SUCCESS = "PARTY_GET_SUCCESS"
export const PARTY_GET_FAIL = "PARTY_GET_FAIL"

//delete-party data
export const PARTY_DELETE_REQUEST = "PARTY_DELETE_REQUEST"
export const PARTY_DELETE_SUCCESS = "PARTY_DELETE_SUCCESS"
export const PARTY_DELETE_FAIL = "PARTY_DELETE_FAIL"

//get-election data
export const ELECTION_GET_REQUEST = "ELECTION_GET_REQUEST"
export const ELECTION_GET_SUCCESS = "ELECTION_GET_SUCCESS"
export const ELECTION_GET_FAIL = "ELECTION_GET_FAIL"

//add-election data
export const ELECTION_POST_REQUEST = "ELECTION_POST_REQUEST"
export const ELECTION_POST_SUCCESS = "ELECTION_POST_SUCCESS"
export const ELECTION_POST_FAIL = "ELECTION_POST_FAIL"

//delete-party data
export const ELECTION_DELETE_REQUEST = "ELECTION_DELETE_REQUEST"
export const ELECTION_DELETE_SUCCESS = "ELECTION_DELETE_SUCCESS"
export const ELECTION_DELETE_FAIL = "ELECTION_DELETE_FAIL"

//party-connection data
export const PARTYCONNECTION_GET_REQUEST = "PARTYCONNECTION_GET_REQUEST"
export const PARTYCONNECTION_GET_SUCCESS = "PARTYCONNECTION_GET_SUCCESS"
export const PARTYCONNECTION_GET_FAIL = "PARTYCONNECTION_GET_FAIL"

//add-party-connection data
export const PARTY_CONNECTION_POST_REQUEST = "PARTY_CONNECTION_POST_REQUEST"
export const PARTY_CONNECTION_POST_SUCCESS = "PARTY_CONNECTION_POST_SUCCESS"
export const PARTY_CONNECTION_POST_FAIL = "PARTY_CONNECTION_POST_FAIL"